### CADASTRAR CARRO
POST http://localhost:5117/api/carro/cadastrar
Content-Type: application/json

{
  "placa": "ABC-1234",
  "modelo": "Fiat Uno"
}

### LISTAR TODOS OS CARROS
GET http://localhost:5117/api/carro/listar
Accept: application/json

### REMOVER CARRO
DELETE http://localhost:5117/api/carro/remover/{ID}

### ALTERAR CARRO
PATCH http://localhost:5117/api/carro/alterar/6d97134d-70b7-4005-a5e9-d81c2ba72ca2
Content-Type: application/json

{
    "placa": "XYZ-5678",
    "modelo": "Chevrolet Onix"
}

### (ESTACIONAR)
POST http://localhost:5117/api/carro/entrada
Content-Type: application/json

{
    "placa": "CCC-1234",
    "modelo": "AAAAAhaHHHH"
}


### LISTAR VEÍCULOS ESTACIONADOS
GET http://localhost:5117/api/carro/estacionados
Accept: application/json

### SAÍDA DE VEÍCULO (DESOCUPAR VAGA)
POST http://localhost:5117/api/carro/saida/ce425f69-42c5-41e2-be6b-ef14164f32d3



### RELATÓRIO DIÁRIO DE SAÍDAS
GET http://localhost:5117/api/carro/relatorio-diario
Accept: application/json